/*
 * This source file was generated by the Gradle 'init' task
 */
package com.parkinglot.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ParkingCliApp classUnderTest = new ParkingCliApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
