
plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
}

group = "com.parkinglot.app"
version = "1.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.guice)
    implementation(libs.jackson)
    implementation(libs.jackson.jsr310)

    implementation(libs.picocli)
    annotationProcessor(libs.picocli.codegen)

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = 'com.parkinglot.app.ParkingCliApp'
}

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

compileJava {
    options.compilerArgs += ["-Aproject=${project.group}/${project.name}"]
}

tasks.named("jar") {
    manifest {
        attributes(
                'Main-Class': 'com.parkinglot.app.ParkingCliApp'
        )
    }
    // Merge runtime dependencies into a final Fat JAR
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
